{{$name := "gpu-tracker-consumer"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}
  labels:
    app: {{$name}}
spec:
  selector:
    matchLabels:
      app: {{$name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{$name}}
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.app.database.pvcName }}
      containers:
      - name: {{$name}}
        image: {{.Values.app.image.registry}}/gpu-tracker-consumer
        imagePullPolicy: Always # always pull image since we are not tagging our images and therefore kubernetes will assume that it already has the latest one
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: BOOTSTRAP_SERVERS
          value: {{.Release.Name}}-kafka:9092
        - name: SCHEMA_REGISTRY_URL
          value: http://{{ .Values.schemaRegistry.hostname }}:{{ .Values.schemaRegistry.port }}
        - name: DATABASE_CONNECTION_STRING
          value: {{ .Values.app.database.sqliteConnectionString }}
        - name: TOPIC_NAME
          value: {{ .Values.topicName }}
                