{{$name := "gpu-tracker-app"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}
  labels:
    app: {{$name}}
spec:
  selector:
    matchLabels:
      app: {{$name}}
  replicas: {{.Values.app.replicas}}
  template:
    metadata:
      labels:
        app: {{$name}}
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.app.database.pvcName }}
      containers:
      - name: {{$name}}
        image: {{.Values.app.image.registry}}/gpu-tracker-app
        imagePullPolicy: Always # always pull image since we are not tagging our images and therefore kubernetes will assume that it already has the latest one
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: DATABASE_CONNECTION_STRING
          value: {{ .Values.app.database.sqliteConnectionString }}
        - name: SMTP_SERVER
          value: {{ .Values.smtp.host }}
        - name: SMTP_FROM
          value: {{ .Values.smtp.senderAddress }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$name}}
spec:
  type: LoadBalancer
  selector:
    app: {{$name}}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
                