{{$name := "gpu-tracker-producer"}}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{$name}}
spec:
  schedule: "* * * * *" # every minute
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{$name}}
              image: {{.Values.app.image.registry}}/gpu-tracker-producer
              imagePullPolicy: Always # always pull image since we are not tagging our images and therefore kubernetes will assume that it already has the latest one
              envFrom:
              - configMapRef:
                  name: kafka-configmap