apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.schemaRegistry.hostname }}
  labels:
    app: {{ .Values.schemaRegistry.hostname }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.schemaRegistry.hostname }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.schemaRegistry.hostname }}
    spec:
      containers:
      - name: {{ .Values.schemaRegistry.hostname }}
        image: confluentinc/cp-schema-registry
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: {{ .Values.schemaRegistry.port }}
            # config value tranformation system: https://docs.confluent.io/platform/current/installation/docker/config-reference.html#docker-configuration-parameters-for-cp
            # configuration options: https://docs.confluent.io/platform/current/schema-registry/installation/config.html#schema-canonicalize-on-consume
        envFrom:
        - configMapRef:
            name: kafka-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.schemaRegistry.hostname }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.schemaRegistry.hostname }}
  ports:
    - protocol: TCP
      port: {{ .Values.schemaRegistry.port }}
      targetPort: {{ .Values.schemaRegistry.port }}
            
