topicName: Gpus

app:
  replicas: 1
  database:
    sqliteConnectionString: "Data Source=/data/GpuTracker.db"
    pvName: sqlite
    pvcName: sqlite
  image:
    registry: docker.io/se22m001

smtp:
  hostname: gpu.tracker.com # used by the smtp server to identify itself
  host: smtp-server # used by the application (= like a connection string)
  senderAddress: noreply@gpu.tracker.com

kafkaUi:
  hostname: kafka-ui
  port: 8080

schemaRegistry:
  hostname: kafka-schema-registry
  port: 8081

kafka:
  # https://artifacthub.io/packages/helm/bitnami/kafka

  replicaCount: 3
  defaultReplicationFactor: 3
  offsetsTopicReplicationFactor: 3
  numIoThreads: 4
  numPartitions: 3

  pdb:
    create: true

  rbac:
    create: true

  provisioning:
    enabled: true
    replicationFactor: 3
    numPartitions: 3
    topics:
      - name: Gpus # https://stackoverflow.com/a/72628337

  volumePermissions:
    enabled: true
