{{$name := "gpu-tracker-consumer"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}
  labels:
    app: {{$name}}
spec:
  selector:
    matchLabels:
      app: {{$name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{$name}}
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
      containers:
      - name: {{$name}}
        image: se22m001/gputracker-consumer
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: BOOTSTRAP_SERVERS
          value: {{.Release.Name}}-kafka:9092
        - name: SCHEMA_REGISTRY_URL
          value: http://kafka-schema-registry:8081
        - name: DATABASE_CONNECTION_STRING
          value: "Data Source=/data/GpuTracker.db"
                