{{$name := "kafka-ui"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{$name}}
spec:
  selector:
    matchLabels:
      app: {{$name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{$name}}
    spec:
      containers:
      - name: {{$name}}
        image: provectuslabs/kafka-ui
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 8080
        env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: gpu-tracker
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: {{.Release.Name}}-kafka:9092
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY	
              value: http://kafka-schema-registry:8081
---
apiVersion: v1
kind: Service
metadata:
  name: {{$name}}
spec:
  selector:
    app: {{$name}}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
            
