apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafkaUi.hostname }}
  labels:
    app: {{ .Values.kafkaUi.hostname }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.kafkaUi.hostname }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.kafkaUi.hostname }}
    spec:
      containers:
      - name: {{ .Values.kafkaUi.hostname }}
        image: provectuslabs/kafka-ui
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: {{ .Values.kafkaUi.port }}
        env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: {{.Release.Name}}
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: {{.Release.Name}}-kafka:9092
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY	
              value: http://{{.Values.schemaRegistry.hostname}}:{{.Values.schemaRegistry.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafkaUi.hostname }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.kafkaUi.hostname }}
  ports:
    - protocol: TCP
      port: {{ .Values.kafkaUi.port }}
      targetPort: {{ .Values.kafkaUi.port }}
            
