{{$name := "kafka-schema-registry"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$name}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{$name}}
spec:
  selector:
    matchLabels:
      app: {{$name}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{$name}}
    spec:
      containers:
      - name: {{$name}}
        image: confluentinc/cp-schema-registry
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 8081
        env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: {{.Release.Name}}-kafka:9092
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: {{$name}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$name}}
spec:
  selector:
    app: {{$name}}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
            
