apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: {{ .Values.pvName }}
  hostPath:
    path: /var/lib/k8s-pvs/sqlite
