apiVersion: v2
name: GpuTrackerHelmChart
description: A Helm chart for Kubernetes
type: application

version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: kafka
    version: "21.2.0"
    repository: "https://charts.bitnami.com/bitnami"
