pvName: sqlite
pvcName: sqlite

kafka:
  # https://artifacthub.io/packages/helm/bitnami/kafka

  defaultReplicationFactor: 3
  offsetsTopicReplicationFactor: 3
  numIoThreads: 4
  numPartitions: 3

  # what about listeners and advertised listeners?
  replicaCount: 1

  # https://github.com/bitnami/charts/issues/1024
  # advertisedListeners:

  pdb:
    create: true

  rbac:
    create: true

  # what about resource requests and limits?

  # service:
  #   type: LoadBalancer

  provisioning:
    enabled: true
    replicationFactor: 1
    numPartitions: 1
    topics:
      - name: "Gpus" # https://stackoverflow.com/a/72628337
    
  # https://github.com/bitnami/charts/tree/main/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster
  externalAccess:
    enabled: true
    autoDiscovery:
      enabled: true

  volumePermissions:
    enabled: true

  # service:
  #   type: LoadBalancer